/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    IconfontIcon: typeof import('./src/components/IconfontIcon.vue')['default']
    IconFontIcon: typeof import('./src/components/Icon/IconfontIcon.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconNetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    IconSvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    NetIcon: typeof import('./src/components/NetIcon.vue')['default']
    OthersReloadPrompt: typeof import('./src/components/others/ReloadPrompt.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
